
INSERT INTO PET(ID, SPECIES) VALUES (1, 'Dog');
INSERT INTO PET(ID, SPECIES) VALUES (2, 'Cat');

INSERT INTO USER(ID, NAME, AGE, PET_ID) VALUES (1, 'Misha', 27, 1);
INSERT INTO USER(ID, NAME, AGE, PET_ID) VALUES (2, 'Anna', 24, 1);
INSERT INTO USER(ID, NAME, AGE, PET_ID) VALUES (3, 'Andrey', 32, 1);
INSERT INTO USER(ID, NAME, AGE, PET_ID) VALUES (4, 'Tanya', 45, 2);

