DROP TABLE IF EXISTS PET, USER;

CREATE TABLE PET(
        ID BIGINT PRIMARY KEY AUTO_INCREMENT,
        SPECIES VARCHAR(256)
);

CREATE TABLE USER(
        ID BIGINT PRIMARY KEY AUTO_INCREMENT,
        NAME VARCHAR(256),
        AGE INT,
        PET_ID BIGINT REFERENCES PET(ID)
);